service: NotesAPIServerless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: alex
  region: eu-north-1
  iam:
    role: arn:aws:iam::879587532835:role/notes-cloud


plugins:
 - serverless-webpack


package:
 individually: true



functions:
  getNotes:
   handler: functions/getNotes/index.handler
   events:
     - httpApi:
         path: '/notes'
         method: GET
  postNotes:
    handler: functions/postNotes/index.handler
    events:
      - httpApi:
         path: '/notes'
         method: POST




resources:
  Resources:
    notesDb:
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: notes-db
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    
