service: NotesAPIServerless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: alex
  region: eu-north-1


plugins:
 - serverless-webpack


package:
 individually: true



functions:
  getNotes:
   handler: functions/getNotes/index.handler
   events:
     - httpApi:
         path: '/notes'
         method: GET
    
